export const countryCodes = [
  { code: '+27', name: 'South Africa', flag: '🇿🇦' },
  { code: '+44', name: 'United Kingdom', flag: '🇬🇧' },
  { code: '+1', name: 'United States', flag: '🇺🇸' },
  { code: '+61', name: 'Australia', flag: '🇦🇺' },
  { code: '+64', name: 'New Zealand', flag: '🇳🇿' },
  { code: '+353', name: 'Ireland', flag: '🇮🇪' },
  { code: '+91', name: 'India', flag: '🇮🇳' },
  { code: '+971', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: '+254', name: 'Kenya', flag: '🇰🇪' },
  { code: '+234', name: 'Nigeria', flag: '🇳🇬' },
  { code: '+260', name: 'Zambia', flag: '🇿🇲' },
  { code: '+263', name: 'Zimbabwe', flag: '🇿🇼' },
  { code: '+267', name: 'Botswana', flag: '🇧🇼' },
  { code: '+264', name: 'Namibia', flag: '🇳🇦' },
  { code: '+266', name: 'Lesotho', flag: '🇱🇸' },
  { code: '+268', name: 'Eswatini', flag: '🇸🇿' },
  { code: '+258', name: 'Mozambique', flag: '🇲🇿' },
  { code: '+244', name: 'Angola', flag: '🇦🇴' },
  { code: '+243', name: 'DR Congo', flag: '🇨🇩' },
  { code: '+250', name: 'Rwanda', flag: '🇷🇼' },
].sort((a, b) => a.name.localeCompare(b.name));